### PR TITLE
Support for ethers-v5

### PR DESCRIPTION
**Pull request by tuler**
@typechain/ethers-v5 is available in beta

### CODE REVIEW

**Comment by nventuro** [comment]
Is there anything blocking this from being merged? It'd be great to have support for Ethers 5 - this is the only thing stopping me from using this plugin. Thanks!

**Comment by dbeal-eth** [comment]
had to hack my `node_modules` in order to get this to work today, it seems that fresh buidler sample project is no longer compatible with the module if you add it, because it uses ethers-v5. please merge this!

**Comment by dbeal-eth** [comment]
@rhlsthrm ?

**Comment by rhlsthrm** [comment]
Hey @KillerByte thanks so much for the PR! Sorry for the huge delay in merging this.

**Comment by dl00** [comment]
wasn't my PR but glad I pinged :)

**Comment by rhlsthrm** [comment]
Yep, thanks again! I got everything updated and cleaned up.

**Pull request merged**
